
version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
  frontend:
    build:
      context: ./frontend
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - backend
